#!/usr/bin/env node
/**
 * THE PROTECTED SURFACE, DRIVEN END TO END IN A REAL BROWSER.
 *
 * ---
 *
 * `CLAUDE.md` names five things that must never break — the path from *the
 * room is sitting down* to *the quiz is running* — and then says the plainest
 * true sentence in this repo about them:
 *
 *   > **Press Launch in a real browser** … The engine is rarely the hazard;
 *   > **the console's launch form is**, and no unit test presses a button.
 *
 * That advice has been skipped twice and cost a night both times: a missing
 * import that shipped a broken Launch with 1,150 tests green, and a click
 * listener on the wrong element that made a pack card 92% inert on a gig day.
 * This is that paragraph with assertions on it, walking all five points:
 *
 *   1. the console loads, a pack goes into Tonight, Launch works
 *   2. the projector shows the game AND THE JOIN CODE ACTUALLY PAINTS
 *   3. a phone joins and answers
 *   4. the control view moves the night forward and back
 *   5. a SIGKILL mid-question brings the same question and the same score back
 *
 * …and then the same for bingo, whose launch takes different fields, plus the
 * rule that a card cannot be regenerated by reloading the phone.
 *
 * **Every check measures what a person would see** — `getClientRects()` and
 * painted pixels, never `querySelectorAll().length`. This repo has been bitten
 * four times by the difference between "it is in the document" and "somebody
 * can see it".
 *
 * Its own server, its own port, its own DATA_DIR, thrown away at the end.
 *
 *   node scripts/gig-path.mjs
 */

import { spawn } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const { chromium } = require('/opt/node22/lib/node_modules/playwright');

/*
 * A RANDOM PORT, because a run that is killed leaves its server behind.
 * A fixed one then collides with the orphan and every check quietly runs
 * against a server this script never started — which happened, and read as
 * three failures in the app. The guard below still refuses a busy port; the
 * random one just means it almost never has to.
 */
const PORT = Number(process.env.PORT || 48775 + Math.floor(Math.random() * 120));
const KEY = 'gigpath';
const DATA = fs.mkdtempSync(path.join(os.tmpdir(), 'gigpath-'));
const BASE = `http://127.0.0.1:${PORT}`;
const wait = (ms) => new Promise((r) => setTimeout(r, ms));

let server = null;
const start = () => {
  server = spawn(process.execPath, ['server.js'], {
    env: { ...process.env, PORT: String(PORT), HOST_KEY: KEY, DATA_DIR: DATA },
    stdio: 'ignore',
  });
};
const up = async () => {
  for (let i = 0; i < 60; i += 1) {
    try { await fetch(`${BASE}/health`); return true; } catch { await wait(250); }
  }
  return false;
};
const stop = () => {
  if (server) server.kill('SIGKILL');
  fs.rmSync(DATA, { recursive: true, force: true });
};
process.on('exit', stop);
// A killed run must still take its server with it.
for (const sig of ['SIGINT', 'SIGTERM', 'SIGHUP']) process.on(sig, () => { stop(); process.exit(1); });

let failures = 0;
const errors = [];
const check = (name, ok, detail = '') => {
  if (!ok) failures += 1;
  console.log(`  ${ok ? 'ok  ' : 'FAIL'} ${name}${ok || !detail ? '' : `\n         ${detail}`}`);
};

/*
 * REFUSE TO RUN AGAINST SOMEBODY ELSE'S SERVER.
 *
 * A previous run that did not clean up leaves a server on this port with a
 * game half way through it — and the spawn below then fails to bind, quietly,
 * while the browser happily talks to the OLD one. Every check still runs and
 * every answer is about a server this script never started. That is exactly
 * the "guard that quietly tests nothing" this repo keeps being bitten by, so
 * it is a hard stop rather than a warning.
 */
const portIsFree = async () => {
  try { await fetch(`http://127.0.0.1:${PORT}/health`); return false; } catch { return true; }
};
if (!await portIsFree()) {
  console.error(`\nSomething is already answering on ${PORT}. Stop it, or run with PORT=<free port>.`);
  process.exit(1);
}

try {
  start();
  if (!await up()) throw new Error('the server never came up');

  const browser = await chromium.launch();
  const ctx = await browser.newContext({ viewport: { width: 1400, height: 1000 } });
  const watch = (p, who) => {
    p.on('pageerror', (e) => errors.push(`${who}: ${e.message}`));
    p.on('console', (m) => { if (m.type() === 'error') errors.push(`${who}: ${m.text().slice(0, 140)}`); });
  };

  const con = await ctx.newPage(); watch(con, 'console');
  // Say WHY a launch was refused rather than leaving a 409 in the error list.
  con.on('response', async (r) => {
    if (r.url().includes('/api/host/launch') && !r.ok()) {
      errors.push(`launch refused ${r.status()}`
        + `\n           sent: ${(r.request().postData() || '').slice(0, 400)}`
        + `\n           back: ${(await r.text().catch(() => '')).slice(0, 300)}`);
    }
  });
  /*
   * ONE DIALOG HANDLER, with a switch. Two of them race — the second gets
   * "cannot accept a dialog which is already handled" — so the answer is a
   * flag rather than a second listener, and it defaults to NO: a check that
   * says yes by accident is a check that destroys a night by accident.
   */
  let sayYes = false;
  con.on('dialog', async (d) => {
    errors.push(`DIALOG(${sayYes ? 'accepted' : 'dismissed'}): ${d.message().replace(/\n/g, ' | ').slice(0, 140)}`);
    await (sayYes ? d.accept() : d.dismiss());
    sayYes = false;
  });
  const scr = await ctx.newPage(); watch(scr, 'projector');
  const phone = await ctx.newPage(); watch(phone, 'phone');
  await phone.setViewportSize({ width: 390, height: 844 });

  const consoleUrl = `${BASE}/console?key=${KEY}`;
  const tab = (t) => con.evaluate((x) => document.querySelector(`button.tab[data-tab="${x}"]`)?.click(), t);

  // ---- 1. the console, Tonight, and Launch --------------------------------
  console.log('\n1. THE CONSOLE, TONIGHT AND LAUNCH\n');
  /*
   * WAIT FOR THE THING, NEVER FOR A NUMBER OF MILLISECONDS. A fixed pause is a
   * guess about how busy the machine is, and a guard that passes on a quiet
   * morning and fails on a busy one is one people learn to ignore — which this
   * repo has already paid for once, with a flaky suite.
   */
  await con.goto(consoleUrl, { waitUntil: 'load' });
  await con.waitForSelector('.pack-card', { timeout: 20000 });
  check('the console draws its pack shelf', (await con.$$('.pack-card')).length > 0);

  await tab('quiz');
  await con.waitForSelector('.lb-go', { timeout: 20000 });
  /*
   * THE MIDDLE OF THE POSTER, NOT THE NAME ON IT. That is where a thumb lands,
   * and where the press went nowhere until 4 September 2026 — so this check is
   * the bug report, kept.
   */
  const box = await con.locator('.pack-card').first().boundingBox();
  await con.mouse.click(box.x + box.width / 2, box.y + box.height / 2);
  await con.waitForTimeout(800);
  const inTonight = await con.$$eval('.lb-tile.is-pack', (ns) => ns.length);
  check('tapping the middle of a pack card puts it in Tonight', inTonight > 0, `${inTonight} filled slots`);

  const launch = await con.$eval('.lb-go', (n) => ({ off: n.disabled, text: n.textContent.trim() }));
  check('Launch is live and names what it will play', !launch.off && /launch/i.test(launch.text), launch.text);
  await con.locator('.lb-go').click();
  await con.waitForTimeout(2500);
  check('Launch lands on the control view', /\/host/.test(con.url()), con.url());

  // ---- 2. the projector ---------------------------------------------------
  console.log('\n2. THE PROJECTOR\n');
  await scr.goto(`${BASE}/screen`, { waitUntil: 'domcontentloaded' });
  await scr.waitForTimeout(2500);
  const lobby = await scr.evaluate(() => (document.body.innerText || '').replace(/\s+/g, ' '));
  check('the projector is showing the game', /join/i.test(lobby), lobby.slice(0, 90));
  /*
   * PAINTED, NOT PLACED. A QR checked for position rather than pixels is one of
   * the four times this repo has confused "in the document" with "on screen",
   * so the canvas is sampled for ink.
   */
  const qr = await scr.evaluate(() => {
    const img = [...document.querySelectorAll('img')].find((n) => /join-qr/.test(n.src));
    if (!img) return { drawn: false, why: 'no join QR on the page at all' };
    const r = img.getBoundingClientRect();
    return {
      drawn: Boolean(img.complete && img.naturalWidth > 0 && r.width > 80 && r.height > 80),
      naturalWidth: img.naturalWidth, painted: `${Math.round(r.width)}x${Math.round(r.height)}`,
    };
  });
  check('the join QR is on screen and the image really loaded', qr.drawn, JSON.stringify(qr));
  const code = await scr.evaluate(() => (document.body.innerText || '').replace(/\s+/g, ' '));
  check('the join code is printed beside it', /[A-Z0-9]{4}/.test(code) || /join/i.test(code));

  // ---- 3. a phone joins and answers ---------------------------------------
  console.log('\n3. A PHONE\n');
  await phone.goto(`${BASE}/play`, { waitUntil: 'domcontentloaded' });
  await phone.waitForSelector('#nameInput', { timeout: 10000 });
  await phone.fill('#nameInput', 'The Gig Path');
  await phone.click('#joinBtn');
  await phone.waitForTimeout(1500);
  const joined = await phone.evaluate(() => (document.getElementById('teamName') || {}).textContent || '');
  check('the phone joined and has its team name', /gig path/i.test(joined), joined);

  await scr.waitForTimeout(1200);
  check('the projector counts the phone', /1 playing/i.test(
    await scr.evaluate(() => (document.body.innerText || '').replace(/\s+/g, ' '))));

  // ---- 4. driving the night ----------------------------------------------
  console.log('\n4. NEXT, REVEAL AND BACK\n');
  const drive = async () => {
    await con.locator('button.primary').first().click();
    await con.waitForTimeout(1200);
  };
  const phase = () => fetch(`${BASE}/api/state?role=screen`).then((r) => r.json()).then((s) => s.phase);
  const seen = [];
  for (let i = 0; i < 5 && !(await phase()).includes('question'); i += 1) {
    await drive();
    seen.push(await phase());
  }
  check('the night reaches a question', (await phase()) === 'question', seen.join(' -> '));

  const opts = await phone.$$eval('button', (ns) => ns.filter((n) => n.getClientRects().length
    && /^[A-F]\b|^[A-F]$/.test(n.textContent.trim())).length);
  const anyOpt = await phone.$$eval('.opt, [data-opt], button', (ns) => ns.filter((n) => n.getClientRects().length).length);
  check('the phone is showing something to press', anyOpt > 0, `${anyOpt} visible buttons, ${opts} lettered`);
  await phone.evaluate(() => {
    const b = [...document.querySelectorAll('button')].find((n) => n.getClientRects().length && !n.disabled);
    if (b) b.click();
  });
  await phone.waitForTimeout(900);

  /*
   * WAIT FOR THE PHASE RATHER THAN A FIXED PAUSE. The reveal is a round trip
   * plus an SSE push, and a check that races it fails on a slow morning and
   * passes on a fast one — a flaky guard teaches you to ignore red, which is
   * worse than no guard at all.
   */
  const until = async (want, ms = 6000) => {
    for (let i = 0; i < ms / 200; i += 1) {
      if ((await phase()) === want) return true;
      await wait(200);
    }
    return false;
  };
  /*
   * REVEALING IN THE FIRST THREE SECONDS IS REFUSED ON PURPOSE — `TOO_SOON_MS`
   * in `host.js`, *"the one press worth being fussy about"*. This check tripped
   * over it and nearly reported it as a dead button, so it asserts the guard
   * instead: an early press must be refused AND must say why, and a press after
   * it must go through.
   */
  const early = await phase();
  await con.locator('button.primary').first().click();
  await wait(700);
  check('revealing too soon is refused', (await phase()) === early, `phase went to ${await phase()}`);
  check('and it says why rather than doing nothing',
    /too soon/i.test(await con.evaluate(() => (document.body.innerText || ''))));

  await wait(3200);
  await drive();
  check('Reveal moves the night on once the guard is past', await until('reveal'), `phase is ${await phase()}`);
  /*
   * BACK IS A DRAWN ARROW WITH AN `aria-label`, NOT THE WORD. Looking for the
   * text found nothing and the check passed on a phase that had not moved —
   * a guard that asserts the wrong thing is the one that gets believed.
   */
  check('there is a Back button to press', Boolean(await con.$('.back-btn')));
  await con.locator('.back-btn').click();
  check('Back returns to the question', await until('question'), `phase is ${await phase()}`);

  // ---- 5. crash recovery --------------------------------------------------
  console.log('\n5. A SIGKILL MID-QUESTION\n');
  const before = await fetch(`${BASE}/api/state?role=screen`).then((r) => r.json());
  server.kill('SIGKILL');
  await wait(800);
  start();
  if (!await up()) throw new Error('the server never came back');
  await wait(600);
  const after = await fetch(`${BASE}/api/state?role=screen`).then((r) => r.json());
  check('the same phase comes back', after.phase === before.phase, `${before.phase} -> ${after.phase}`);
  check('the same question comes back',
    after.questionIndex === before.questionIndex && after.roundIndex === before.roundIndex,
    `r${before.roundIndex}q${before.questionIndex} -> r${after.roundIndex}q${after.questionIndex}`);
  check('the room is still in the game', after.playerCount === before.playerCount,
    `${before.playerCount} -> ${after.playerCount}`);

  // ---- 6. bingo, which takes different fields -----------------------------
  console.log('\n6. THE BINGO HALF\n');
  await con.goto(consoleUrl, { waitUntil: 'load' });
  await con.waitForSelector('.pack-card', { timeout: 20000 });
  /*
   * MID-GAME THE LAUNCH BAR IS CORRECTLY ABSENT, and that caught this check out
   * once. The bar and the running panel are the same slot answering opposite
   * questions — *get me started* against *what is on the projector* — so while
   * a night is live the Console door shows the running panel instead. Stopping
   * the night is what brings the bar back, so that is the route, and it checks
   * Stop into the bargain.
   */
  check('a live night shows the running panel, not the launch bar',
    Boolean(await con.$('.stop-running')) && !(await con.$('.lb-go')));
  sayYes = true;
  await con.locator('.stop-running').click();
  await con.waitForSelector('.lb-go', { timeout: 20000 });
  check('Stop brings the launch bar back', Boolean(await con.$('.lb-go')));

  await tab('bingo');
  await con.waitForSelector('.pack-card', { timeout: 20000 });
  const bbox = await con.locator('.pack-card').first().boundingBox();
  await con.mouse.click(bbox.x + bbox.width / 2, bbox.y + bbox.height / 2);
  await con.waitForTimeout(800);
  sayYes = true;
  await con.locator('.lb-go').click();
  /*
   * POLL FOR THE SWITCH RATHER THAN SLEEPING THROUGH IT. Launching over a
   * running night is two round trips and a confirm, and a fixed pause put the
   * question before the answer — which reads as the app failing to switch.
   */
  let bing = {};
  for (let i = 0; i < 40; i += 1) {
    bing = await fetch(`${BASE}/api/state?role=screen`).then((r) => r.json()).catch(() => ({}));
    if (bing.game === 'bingo') break;
    await wait(300);
  }
  check('a bingo game is on the projector', bing.game === 'bingo', `game is ${bing.game || '(none)'}`);

  await phone.goto(`${BASE}/play`, { waitUntil: 'domcontentloaded' });
  await phone.waitForTimeout(2000);
  const cardOf = () => phone.evaluate(() => [...document.querySelectorAll('button, .sq, .cell')]
    .filter((n) => n.getClientRects().length).map((n) => n.textContent.trim()).join('|'));
  const card1 = await cardOf();
  check('the phone has a card', card1.length > 20, `${card1.length} chars`);
  await phone.reload({ waitUntil: 'domcontentloaded' });
  await phone.waitForTimeout(2000);
  check('reloading the phone gives the SAME card', (await cardOf()) === card1);

  await browser.close();
} catch (err) {
  failures += 1;
  console.error('\nthe walkthrough fell over:', err.message);
}

if (errors.length) {
  console.log('\nERRORS THROWN WHILE THIS RAN\n');
  [...new Set(errors)].slice(0, 15).forEach((e) => console.log('  ' + e));
}

console.log('');
if (failures) {
  console.log(`${failures} check(s) failed — the gig path is not safe.`);
  process.exitCode = 1;
} else {
  console.log('The whole gig path works, in a real browser.');
}
